# Generated by Django 4.0.2 on 2022-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/'),
        ),
    ]
