# Generated by Django 4.0.2 on 2022-03-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nickname',
            new_name='user_info',
        ),
    ]
