# Generated by Django 4.0.2 on 2022-02-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'tb_food_images',
            },
        ),
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carb', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('calorie', models.FloatField()),
            ],
            options={
                'db_table': 'tb_food_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=200)),
                ('taste', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tb_user_info',
            },
        ),
        migrations.CreateModel(
            name='FoodImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('food_id', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, related_name='food_info', to='yamm.foodinfo')),
                ('img_id', models.ForeignKey(db_column='food_img', on_delete=django.db.models.deletion.CASCADE, related_name='food_img', to='yamm.foodimage')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='yamm.user')),
            ],
            options={
                'db_table': 'tb_food_images_info',
            },
        ),
    ]
