# Generated by Django 4.0.2 on 2022-02-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=200)),
                ('taste', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tb_user_info',
            },
        ),
    ]
