# Generated by Django 4.0.2 on 2022-03-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phonenumber',
        ),
    ]
