# Generated by Django 4.0.2 on 2022-03-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamm', '0002_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phonenumber',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='./profile_img/'),
        ),
        migrations.DeleteModel(
            name='userLogin',
        ),
    ]
