# Generated by Django 4.0.2 on 2022-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamm', '0002_rename_number_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
