# Generated by Django 4.0.2 on 2022-03-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamm', '0002_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userLogin',
        ),
    ]
